language: ruby
cache: bundler
rvm:
  - 2.2
  - 2.1
  - ruby-head
  - rbx-2
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
    - rvm: jruby-head

addons:
  code_climate:
    repo_token: bee0f6bf8955be05fd8b557f66da5e8f49b90b6c5a92b3a1a750b04bb8c939fb
