language: ruby
cache: bundler
rvm:
  - 2.2
  - 2.1
  - 2.0
  - 1.9.3
  - ruby-head
  - rbx-2
  - jruby-19mode
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
    - rvm: jruby-19mode
    - rvm: jruby-head
